/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVista;

import CapaLogica.Adicional;
import CapaLogica.Combo;
import CapaLogica.Cuenta;
import CapaLogica.LineaDetalle;
import CapaLogica.PlatoPrincipal;
import CapaLogica.Producto;
import CapaLogica.Refresco;
import CapaLogica.Tamaño;
import CapaLogica.TipoUsuario;
import CapaLogica.Usuario;
import static CapaVista.JDlgUsuarios.salonero;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabriela
 */
public class FrmCuenta extends javax.swing.JFrame {

    static Cuenta cuenta1;
    Producto producto;
    ArrayList<Adicional> arrayPedidoAdic=new ArrayList<>();
    static int cont=1;
    DefaultTableModel modeloTable=new DefaultTableModel();
    private ArrayList<Producto> arrayProducto= new ArrayList();
     LineaDetalle linea;
    public FrmCuenta() {
        initComponents();
       modeloTable= (DefaultTableModel) jTblPedidos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroupPedidos = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtNumCuenta = new javax.swing.JTextField();
        jSpnMesa = new javax.swing.JSpinner();
        jTxtFecha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRdbPlato = new javax.swing.JRadioButton();
        jRdbRefresco = new javax.swing.JRadioButton();
        jRdbAdicional = new javax.swing.JRadioButton();
        jRdbCombo = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCbxPlato = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jCbxResfresco = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jCbxAdicional = new javax.swing.JComboBox<>();
        jTxtCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextIndicaciones = new javax.swing.JTextField();
        jPnlTamaño = new javax.swing.JPanel();
        jChbGrande = new javax.swing.JCheckBox();
        jTxtExtra = new javax.swing.JTextField();
        jPnlCombo = new javax.swing.JPanel();
        jChbAgrandar = new javax.swing.JCheckBox();
        jChbRefil = new javax.swing.JCheckBox();
        jTextRefil = new javax.swing.JTextField();
        jTextAgrandar = new javax.swing.JTextField();
        jCbxAdComb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblPedidos = new javax.swing.JTable();
        jBtnEliminarPedidos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtaFactura = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtSubtotal = new javax.swing.JTextField();
        jTxtImpuesto = new javax.swing.JTextField();
        jTxtServicio = new javax.swing.JTextField();
        jTxtTotal = new javax.swing.JTextField();
        jBtnAñadirPedido = new javax.swing.JButton();
        jBtnLimpiar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTxtHora = new javax.swing.JTextField();
        jBtnNuevoPedido = new javax.swing.JButton();
        jBtnCrearCuenta = new javax.swing.JButton();
        jBtnPago = new javax.swing.JButton();
        jLbDes = new javax.swing.JLabel();
        jTxtDesc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Número de Cuenta: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Número de Mesa: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Fecha: ");

        jTxtNumCuenta.setEditable(false);

        jSpnMesa.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jTxtFecha.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        BtnGroupPedidos.add(jRdbPlato);
        jRdbPlato.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRdbPlato.setText("Plato Principal");
        jRdbPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbPlatoActionPerformed(evt);
            }
        });

        BtnGroupPedidos.add(jRdbRefresco);
        jRdbRefresco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRdbRefresco.setText("Refresco");
        jRdbRefresco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbRefrescoActionPerformed(evt);
            }
        });

        BtnGroupPedidos.add(jRdbAdicional);
        jRdbAdicional.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRdbAdicional.setText("Adicional");
        jRdbAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbAdicionalActionPerformed(evt);
            }
        });

        BtnGroupPedidos.add(jRdbCombo);
        jRdbCombo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRdbCombo.setText("Combo");
        jRdbCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRdbPlato)
                    .addComponent(jRdbRefresco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRdbAdicional)
                    .addComponent(jRdbCombo))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdbPlato)
                    .addComponent(jRdbAdicional))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdbRefresco)
                    .addComponent(jRdbCombo))
                .addGap(24, 24, 24))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Plato Principal");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Refresco");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Adicional");

        jLabel8.setText("Cantidad ");

        jLabel9.setText("Indicaciones de producto");

        jPnlTamaño.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño"));

        jChbGrande.setText("Grande");
        jChbGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbGrandeActionPerformed(evt);
            }
        });

        jTxtExtra.setEditable(false);

        javax.swing.GroupLayout jPnlTamañoLayout = new javax.swing.GroupLayout(jPnlTamaño);
        jPnlTamaño.setLayout(jPnlTamañoLayout);
        jPnlTamañoLayout.setHorizontalGroup(
            jPnlTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTamañoLayout.createSequentialGroup()
                .addComponent(jChbGrande)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlTamañoLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jTxtExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPnlTamañoLayout.setVerticalGroup(
            jPnlTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTamañoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChbGrande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPnlCombo.setBorder(javax.swing.BorderFactory.createTitledBorder("Combo"));

        jChbAgrandar.setText("Agrandar");
        jChbAgrandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbAgrandarActionPerformed(evt);
            }
        });

        jChbRefil.setText("Refil");
        jChbRefil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbRefilActionPerformed(evt);
            }
        });

        jTextRefil.setEditable(false);

        jTextAgrandar.setEditable(false);

        jLabel4.setText("Segundo Adicional");

        javax.swing.GroupLayout jPnlComboLayout = new javax.swing.GroupLayout(jPnlCombo);
        jPnlCombo.setLayout(jPnlComboLayout);
        jPnlComboLayout.setHorizontalGroup(
            jPnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlComboLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlComboLayout.createSequentialGroup()
                        .addComponent(jChbRefil)
                        .addGap(18, 18, 18)
                        .addComponent(jTextRefil, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlComboLayout.createSequentialGroup()
                        .addComponent(jChbAgrandar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextAgrandar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66)
                .addGroup(jPnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jCbxAdComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPnlComboLayout.setVerticalGroup(
            jPnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlComboLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jChbAgrandar)
                        .addComponent(jTextAgrandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGroup(jPnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlComboLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChbRefil)
                            .addComponent(jTextRefil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jPnlComboLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jCbxAdComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPnlCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbxAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jCbxPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)
                                .addComponent(jTextIndicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jCbxResfresco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPnlTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextIndicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(25, 25, 25)
                .addComponent(jCbxPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jCbxResfresco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPnlTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jCbxAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPnlCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Cantidad", "Indicaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTblPedidos);

        jBtnEliminarPedidos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnEliminarPedidos.setText("Eliminar producto");
        jBtnEliminarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarPedidosActionPerformed(evt);
            }
        });

        jTxtaFactura.setEditable(false);
        jTxtaFactura.setColumns(20);
        jTxtaFactura.setRows(5);
        jScrollPane1.setViewportView(jTxtaFactura);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Subtotal:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Impuesto:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Sevicio:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Total:");

        jTxtSubtotal.setEditable(false);

        jTxtImpuesto.setEditable(false);

        jTxtServicio.setEditable(false);

        jTxtTotal.setEditable(false);

        jBtnAñadirPedido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnAñadirPedido.setText("Añadir pedido");
        jBtnAñadirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAñadirPedidoActionPerformed(evt);
            }
        });

        jBtnLimpiar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnLimpiar.setText("Limpiar Pedido");
        jBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarActionPerformed(evt);
            }
        });

        jBtnSalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Hora:");

        jTxtHora.setEditable(false);

        jBtnNuevoPedido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnNuevoPedido.setText("Nuevo pedido");
        jBtnNuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoPedidoActionPerformed(evt);
            }
        });

        jBtnCrearCuenta.setText("Crear cuenta");
        jBtnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearCuentaActionPerformed(evt);
            }
        });

        jBtnPago.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnPago.setText("Pago de Cuenta");
        jBtnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPagoActionPerformed(evt);
            }
        });

        jLbDes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbDes.setText("Descuento");

        jTxtDesc.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnAñadirPedido)
                                    .addComponent(jBtnNuevoPedido)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtnEliminarPedidos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtFecha))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpnMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jBtnCrearCuenta)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLbDes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jTxtImpuesto)
                            .addComponent(jTxtServicio)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(jBtnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jBtnPago, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnSalir)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnCrearCuenta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jSpnMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jTxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jTxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnEliminarPedidos, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBtnAñadirPedido)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnNuevoPedido))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBtnLimpiar)
                                .addGap(27, 27, 27)
                                .addComponent(jBtnSalir)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLbDes)
                                    .addComponent(jTxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(jTxtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jTxtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jBtnPago))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      try {
            llenarAdicional();           
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, "Error al cargar el combo de Adicional");
          System.exit(0);
        }
      try {
            llenarPlato();           
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, "Error al cargar el combo de Plato Principal");
          System.exit(0);
        }
     try {
            llenarRefrescos();           
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, "Error al cargar el combo de Refresco");
          System.exit(0);
        }
        

        
            jCbxAdicional.setSelectedIndex(-1);
            jCbxResfresco.setSelectedIndex(-1);
            jCbxPlato.setSelectedIndex(-1);
      jPanel2.setEnabled(false);     
      jCbxAdicional.setEnabled(false);
      jCbxResfresco.setEnabled(false);
      jCbxPlato.setEnabled(false);
      jTxtCantidad.setEditable(false);
      jTextIndicaciones.setEditable(false);
      jCbxAdComb.setVisible(false);
      jTextAgrandar.setVisible(false);
      jTextRefil.setVisible(false);
      jTxtExtra.setVisible(false);
      jLbDes.setVisible(false);
      jTxtDesc.setVisible(false);
      jPnlCombo.setVisible(false);
      jPnlTamaño.setVisible(false);
      jRdbAdicional.setEnabled(false);
      jRdbCombo.setEnabled(false);
      jRdbPlato.setEnabled(false);
      jRdbRefresco.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jRdbPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbPlatoActionPerformed
        jCbxPlato.setEnabled(true);
          jCbxResfresco.setEnabled(false);
        jCbxAdicional.setEnabled(false);
          jPnlTamaño.setVisible(false);
           jTxtExtra.setVisible(false);
           jChbGrande.setVisible(false);
         jChbAgrandar.setEnabled(false);
         jChbGrande.setEnabled(false);
         jChbRefil.setEnabled(false);
         jChbGrande.setEnabled(false);
           jTxtCantidad.setText("1");
           jTextRefil.setVisible(false);     
         jChbAgrandar.setVisible(false);
         jPnlCombo.setVisible(false);
         jChbRefil.setVisible(false);
         jCbxAdComb.setVisible(false);
    }//GEN-LAST:event_jRdbPlatoActionPerformed

    private void jRdbAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbAdicionalActionPerformed
       jCbxAdicional.setEnabled(true);
         jCbxPlato.setEnabled(false);
         jCbxResfresco.setEnabled(false);
          jPnlTamaño.setVisible(true);
          jPnlTamaño.setEnabled(true);
         jTxtExtra.setVisible(true);
         jChbGrande.setVisible(true);
         jChbAgrandar.setEnabled(false);
         jChbGrande.setEnabled(true);
         jChbRefil.setEnabled(false);
         jTxtExtra.setVisible(true);
           jTxtCantidad.setText("1");
           jTextRefil.setVisible(false);     
         jChbAgrandar.setVisible(false);
         jPnlCombo.setVisible(false);
         jChbRefil.setVisible(false);
         jCbxAdComb.setVisible(false);
    }//GEN-LAST:event_jRdbAdicionalActionPerformed

    private void jRdbRefrescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbRefrescoActionPerformed
        jCbxResfresco.setEnabled(true);
        jCbxAdicional.setEnabled(false);
         jCbxPlato.setEnabled(false);
         jPnlTamaño.setVisible(true);
         jTxtExtra.setVisible(true);
         jTxtExtra.setEnabled(true);
         jChbAgrandar.setEnabled(false);
         jChbRefil.setEnabled(false);
         jChbGrande.setEnabled(true);
         jChbGrande.setVisible(true);
           jTxtCantidad.setText("1");
            jTextRefil.setVisible(false);     
         jPnlCombo.setVisible(false);
         jChbRefil.setVisible(false);
         jChbAgrandar.setVisible(false);
         jCbxAdComb.setVisible(false);
         jPnlTamaño.setEnabled(true);
    }//GEN-LAST:event_jRdbRefrescoActionPerformed

    private void jRdbComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbComboActionPerformed
        try {
            llenarSegAdicional();           
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, "Error al cargar el combo de Segundo Adicional");
          System.exit(0);
        }
        jCbxPlato.setEnabled(true);
        jTextAgrandar.setVisible(true);
        jCbxAdicional.setEnabled(true);
        jCbxResfresco.setEnabled(true);
           jTextRefil.setVisible(true);     
         jChbAgrandar.setEnabled(true);
         jChbAgrandar.setVisible(true);
         jPnlCombo.setVisible(true);
         jChbRefil.setEnabled(true);
         jChbRefil.setVisible(true);
         jChbGrande.setEnabled(false);
           jTxtCantidad.setText("1");
           jCbxAdComb.setVisible(true);
           jCbxAdComb.setSelectedIndex(-1);
           jCbxAdComb.setEnabled(true);
           jPnlTamaño.setVisible(false);
           jTxtExtra.setVisible(false);
           jChbGrande.setVisible(false);
    }//GEN-LAST:event_jRdbComboActionPerformed

    private void jBtnAñadirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAñadirPedidoActionPerformed
        Object[] tabla =new Object[5];
        if(jRdbPlato.isSelected()){
           
           PlatoPrincipal plato=(PlatoPrincipal) jCbxPlato.getSelectedItem();
            producto= new PlatoPrincipal(plato.getCodigo(), plato.getNombre(),plato.getPrecioBase());
             linea=new LineaDetalle(producto, Integer.parseInt(jTxtCantidad.getText()));
             linea.setIndicaciones(jTextIndicaciones.getText());
        }else{
            if(jRdbRefresco.isSelected()){
                Refresco refresco= (Refresco) jCbxResfresco.getSelectedItem();
                Tamaño tamaño= (jChbGrande.isSelected())?Tamaño.Grande:Tamaño.Pequeño;
                producto=new Refresco(refresco.getCodigo(),tamaño, refresco.getNombre(),refresco.getPrecioBase());
//                producto.montoExtra();
                 linea=new LineaDetalle(producto, Integer.parseInt(jTxtCantidad.getText()));
                  linea.setIndicaciones("Monto extra: " + String.valueOf(producto.montoExtra()));
                  jTxtExtra.setText(String.valueOf(producto.montoExtra()));
            }else{
                if(jRdbAdicional.isSelected()){
                    Adicional adic=(Adicional) jCbxAdicional.getSelectedItem();
                    Tamaño tamaño= (jChbGrande.isSelected())?Tamaño.Grande:Tamaño.Pequeño;
                    producto=new Adicional(adic.getCodigo(), tamaño, adic.getNombre(), adic.getPrecioBase());
//                    producto.montoExtra();
                      linea=new LineaDetalle(producto, Integer.parseInt(jTxtCantidad.getText()));
                     linea.setIndicaciones("Monto extra: " + String.valueOf(producto.montoExtra()));
                      jTxtExtra.setText(String.valueOf(producto.montoExtra()));
             }else{
                     PlatoPrincipal plato=(PlatoPrincipal) jCbxPlato.getSelectedItem();
                     Refresco refresco= (Refresco) jCbxResfresco.getSelectedItem();
                      Adicional adic1=(Adicional) jCbxAdicional.getSelectedItem();
                      Adicional adic2=(Adicional) jCbxAdComb.getSelectedItem();
                     boolean refil=jChbRefil.isSelected();
                     boolean agrandar=jChbAgrandar.isSelected(); 
                     producto= new Combo(String.valueOf(cont++), plato, refresco,refil , agrandar);
                       ((Combo)producto).agregarAdicional(adic1);
                       ((Combo)producto).agregarAdicional(adic2);
                         jTextRefil.setText(String.valueOf(((Combo)producto).cobroRefil()));
                         jTextAgrandar.setText(String.valueOf(((Combo)producto).cobroAgrandado()));
                      linea=new LineaDetalle(producto, Integer.parseInt(jTxtCantidad.getText()));
                      linea.setIndicaciones(jTextIndicaciones.getText());
                      jLbDes.setVisible(true);
                      jTxtDesc.setVisible(true);
                      jTxtDesc.setText(String.valueOf(((Combo)producto).descuento()));
            }
                
            }
        }
        limpiar();
         
             linea.precioLinea();
            cuenta1.agregarProducto(linea);
            tabla[0]=producto.getCodigo();
            tabla[1]=producto.getNombre();
            tabla[2]=producto.montoTotal();
            tabla[3]=linea.getCantidad();
            tabla[4]=linea.getIndicaciones();
            modeloTable.addRow(tabla);
            jTxtaFactura.setText(cuenta1.toString());
            jTxtSubtotal.setText(String.format("%.2f",cuenta1.subTotal())); 
           jTxtImpuesto.setText(String.format("%.2f",cuenta1.impuestos()));
           jTxtServicio.setText(String.format("%.2f",cuenta1.impServicio()));
           jTxtTotal.setText(String.format("%.2f",cuenta1.Total()));   
     
           jBtnAñadirPedido.setEnabled(false);
           jBtnNuevoPedido.setEnabled(true);
           jPanel1.setEnabled(false); 
           jPanel2.setEnabled(false);
    }//GEN-LAST:event_jBtnAñadirPedidoActionPerformed

    private void jChbRefilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbRefilActionPerformed
           jTextRefil.setVisible(true);     
        
    }//GEN-LAST:event_jChbRefilActionPerformed

    private void jBtnEliminarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarPedidosActionPerformed
         if(jTblPedidos.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"Debe seleccionar el departamento a eliminar");
            return;
        }
         int prod=jTblPedidos.getSelectedRow();
         ArrayList listaEliminar=new ArrayList();
           for (int i = 0; i < cuenta1.getArrayDetalle().size(); i++) {
               listaEliminar.add(cuenta1.getArrayDetalle().get(i));
          }
               cuenta1.getArrayDetalle().clear();
           for (int i = 0; i < listaEliminar.size(); i++) {
            if(i!=prod){
               cuenta1.agregarProducto((LineaDetalle) listaEliminar.get(i));
            }
        }
         modeloTable.removeRow(jTblPedidos.getSelectedRow());
          jTxtaFactura.setText(cuenta1.toString());
          jTxtSubtotal.setText( String.format("%.2f",cuenta1.subTotal())); 
          jTxtImpuesto.setText( String.format("%.2f",cuenta1.impuestos()));
          jTxtServicio.setText( String.format("%.2f",cuenta1.impServicio()));
          jTxtTotal.setText(String.format("%.2f",cuenta1.Total()));   
    }//GEN-LAST:event_jBtnEliminarPedidosActionPerformed

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        limpiar();
        jBtnEliminarPedidos.setEnabled(false);
        jBtnAñadirPedido.setEnabled(false);
        jBtnNuevoPedido.setEnabled(false);
        jBtnPago.setEnabled(false);
        modeloTable.setRowCount(0);
        jTxtFecha.setText("");
        jTxtHora.setText("");
        jTxtImpuesto.setText("");
        jTxtSubtotal.setText("");
        jTxtServicio.setText("");
        jTxtTotal.setText("");
        jTxtaFactura.setText("");
        jCbxPlato.setEnabled(false);
        jCbxAdicional.setEnabled(false);
        jCbxResfresco.setEnabled(false);
        jCbxAdComb.setEnabled(false);
        jCbxAdComb.setVisible(false);
        jChbAgrandar.setEnabled(false);
        jBtnCrearCuenta.setEnabled(true);
        jChbRefil.setEnabled(false);
        jChbGrande.setEnabled(false);
        jTextAgrandar.setVisible(false);
        jTextRefil.setVisible(false);
        jPnlCombo.setVisible(false);
        jPnlTamaño.setVisible(false);
        jTxtExtra.setVisible(false);
        jTxtNumCuenta.setText("");
        
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jBtnNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoPedidoActionPerformed
          jPanel2.setEnabled(true);
       jRdbAdicional.setEnabled(true);
        jRdbCombo.setEnabled(true);
        jRdbPlato.setEnabled(true);
        jRdbRefresco.setEnabled(true);
        BtnGroupPedidos.clearSelection();
        buttonGroup1.clearSelection();
        jCbxAdicional.setSelectedIndex(-1);
        jCbxPlato.setSelectedIndex(-1);
        jCbxResfresco.setSelectedIndex(-1);
        jChbAgrandar.setSelected(false);
          jPnlTamaño.setEnabled(false);
           jTxtExtra.setEnabled(false);
           jChbGrande.setEnabled(false);
        jChbGrande.setSelected(false);
        jChbRefil.setSelected(false);
        jTxtCantidad.setText("");
        jTextIndicaciones.setText("");
        jTxtExtra.setText("");
        jCbxPlato.setEnabled(false);
        jCbxResfresco.setEnabled(false);
        jCbxAdicional.setEnabled(false);
        jBtnAñadirPedido.setEnabled(true);
        jBtnNuevoPedido.setEnabled(false);
        jPanel1.setEnabled(true); 
        jPanel2.setEnabled(true);
        jLbDes.setVisible(false);
        jTxtDesc.setVisible(false);
        jTextAgrandar.setVisible(false);
        jTextRefil.setVisible(false);
       
        jTxtExtra.setVisible(false);
        jCbxAdComb.setEnabled(false);
        jCbxAdComb.setVisible(false);
        jChbAgrandar.setEnabled(false);
      
        jChbRefil.setEnabled(false);
        jChbGrande.setEnabled(false);
 
        jPnlCombo.setVisible(false);
        jPnlTamaño.setVisible(false);
    }//GEN-LAST:event_jBtnNuevoPedidoActionPerformed

    private void jBtnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearCuentaActionPerformed
       crearCuenta();
       jTxtCantidad.setEditable(true);
       jTextIndicaciones.setEditable(true);
       jPanel2.setEnabled(true);
       modeloTable.setRowCount(0);
     jBtnCrearCuenta.setEnabled(false);
      jBtnEliminarPedidos.setEnabled(true);
        jBtnAñadirPedido.setEnabled(true);
        jBtnNuevoPedido.setEnabled(true);
        jBtnPago.setEnabled(true);
         jRdbAdicional.setEnabled(true);
      jRdbCombo.setEnabled(true);
      jRdbPlato.setEnabled(true);
      jRdbRefresco.setEnabled(true);
    }//GEN-LAST:event_jBtnCrearCuentaActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPagoActionPerformed
    
       FrmPagoTarjeta frmPago= new FrmPagoTarjeta();
       frmPago.setVisible(true);
       frmPago.setLocationRelativeTo(this);
    }//GEN-LAST:event_jBtnPagoActionPerformed

    private void jChbGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbGrandeActionPerformed

    }//GEN-LAST:event_jChbGrandeActionPerformed

    private void jChbAgrandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbAgrandarActionPerformed
         jTextAgrandar.setVisible(true);
     
    }//GEN-LAST:event_jChbAgrandarActionPerformed

    public void limpiar(){
      jPanel2.setEnabled(false);
       jRdbAdicional.setEnabled(false);
        jRdbCombo.setEnabled(false);
        jRdbPlato.setEnabled(false);
        jRdbRefresco.setEnabled(false);
        BtnGroupPedidos.clearSelection();
        buttonGroup1.clearSelection();
        jCbxAdicional.setSelectedIndex(-1);
        jCbxPlato.setSelectedIndex(-1);
        jCbxResfresco.setSelectedIndex(-1);
        jChbAgrandar.setSelected(false);
        jCbxAdComb.setSelectedIndex(-1);
        jChbGrande.setSelected(false);
        jChbRefil.setSelected(false);
        jTxtCantidad.setText("");
        jTextIndicaciones.setText("");
        jTxtDesc.setVisible(false);
        jLbDes.setVisible(false);
        jTxtDesc.setText("");
        jTextAgrandar.setText("");
        jTextRefil.setText("");
    }
    public void crearCuenta(){
        Usuario usuario1;
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/yy");
        SimpleDateFormat formatoHoras=new SimpleDateFormat("hh:mm:ss");
      if(JDlgUsuarios.permiso){
         usuario1=new Usuario(TipoUsuario.Administrador);
      } else{
         usuario1=new Usuario(TipoUsuario.Salonero); 
      }
      cuenta1= new Cuenta(usuario1);
      int mesa=(int) jSpnMesa.getValue();
      cuenta1.setNumMesa(mesa);
      jTxtNumCuenta.setText(String.valueOf(cuenta1.getNumCuenta()));
      jTxtFecha.setText(String.valueOf(formatoFecha.format(cuenta1.getFecha())));
      jTxtHora.setText(String.valueOf(formatoHoras.format(cuenta1.getHora())));
    }
    
          
           
    public void llenarAdicional() throws Exception{
     
         jCbxAdicional.removeAllItems();
        arrayProducto=Producto.listadoProducto();
        for (int i = 0; i < arrayProducto.size(); i++) {
           Producto prod=arrayProducto.get(i);
            if(prod instanceof Adicional){
                jCbxAdicional.addItem((Adicional)prod );
                
            }
            
            
        }
        jCbxAdicional.setSelectedIndex(-1);
        
    }
    
    public void llenarSegAdicional() throws Exception{
          jCbxAdComb.removeAllItems();
        arrayProducto=Producto.listadoProducto();
        for (int i = 0; i < arrayProducto.size(); i++) {
           Producto prod=arrayProducto.get(i);
            if(prod instanceof Adicional){
                jCbxAdComb.addItem((Adicional)prod );
                }
            
        }
        jCbxAdComb.setSelectedIndex(-1);

    }
    
    public void llenarRefrescos() throws Exception{
         jCbxResfresco.removeAllItems();
        arrayProducto=Producto.listadoProducto();
      for (int i = 0; i < arrayProducto.size(); i++) {
           Producto prod=arrayProducto.get(i);
            if(prod instanceof Refresco){
                  jCbxResfresco.addItem((Refresco)prod );
            }
          
        }
        jCbxResfresco.setSelectedIndex(-1);

    }
    
    public void llenarPlato() throws Exception{
         jCbxPlato.removeAllItems();
        arrayProducto=Producto.listadoProducto();
       for (int i = 0; i < arrayProducto.size(); i++) {
           Producto prod=arrayProducto.get(i);
            if(prod instanceof PlatoPrincipal){
                  jCbxPlato.addItem((PlatoPrincipal)prod );
            }
        jCbxPlato.setSelectedIndex(-1);

    }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroupPedidos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnAñadirPedido;
    private javax.swing.JButton jBtnCrearCuenta;
    private javax.swing.JButton jBtnEliminarPedidos;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jBtnNuevoPedido;
    private javax.swing.JButton jBtnPago;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<Adicional> jCbxAdComb;
    private javax.swing.JComboBox<Adicional> jCbxAdicional;
    private javax.swing.JComboBox<PlatoPrincipal> jCbxPlato;
    private javax.swing.JComboBox<Refresco> jCbxResfresco;
    private javax.swing.JCheckBox jChbAgrandar;
    private javax.swing.JCheckBox jChbGrande;
    private javax.swing.JCheckBox jChbRefil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbDes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnlCombo;
    private javax.swing.JPanel jPnlTamaño;
    private javax.swing.JRadioButton jRdbAdicional;
    private javax.swing.JRadioButton jRdbCombo;
    private javax.swing.JRadioButton jRdbPlato;
    private javax.swing.JRadioButton jRdbRefresco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpnMesa;
    private javax.swing.JTable jTblPedidos;
    private javax.swing.JTextField jTextAgrandar;
    private javax.swing.JTextField jTextIndicaciones;
    private javax.swing.JTextField jTextRefil;
    private javax.swing.JTextField jTxtCantidad;
    private javax.swing.JTextField jTxtDesc;
    private javax.swing.JTextField jTxtExtra;
    private javax.swing.JTextField jTxtFecha;
    private javax.swing.JTextField jTxtHora;
    private javax.swing.JTextField jTxtImpuesto;
    private javax.swing.JTextField jTxtNumCuenta;
    private javax.swing.JTextField jTxtServicio;
    private javax.swing.JTextField jTxtSubtotal;
    private javax.swing.JTextField jTxtTotal;
    private javax.swing.JTextArea jTxtaFactura;
    // End of variables declaration//GEN-END:variables
}
