/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVista;

import CapaLogica.Contado;
import CapaLogica.Credito;
import CapaLogica.Cuenta;
import CapaLogica.Pago;
import static CapaVista.FrmCuenta.cuenta1;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class FrmPagoTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form FrmPagoTarjeta
     */
      Pago pago1;
    public FrmPagoTarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtgTipoPago = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jRdbEfectivo = new javax.swing.JRadioButton();
        jRbdTarjeta = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTxtNumTarjeta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtCodigoT = new javax.swing.JTextField();
        jCbxTipoTarjeta = new javax.swing.JComboBox<String>();
        jBtnValidarT = new javax.swing.JButton();
        jChxDolares = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jTxtMontoD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtPagoC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtaPAgoResumen = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTxtPago = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnGuardarCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modo de Pago ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        BtgTipoPago.add(jRdbEfectivo);
        jRdbEfectivo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRdbEfectivo.setText("Efectivo");
        jRdbEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbEfectivoActionPerformed(evt);
            }
        });

        BtgTipoPago.add(jRbdTarjeta);
        jRbdTarjeta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRbdTarjeta.setText("Tarjeta");
        jRbdTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbdTarjetaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Numero de tarjeta:");

        jTxtNumTarjeta.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Codigo:");

        jTxtCodigoT.setEnabled(false);
        jTxtCodigoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoTActionPerformed(evt);
            }
        });

        jBtnValidarT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnValidarT.setText("Aceptar");
        jBtnValidarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnValidarTActionPerformed(evt);
            }
        });

        jChxDolares.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jChxDolares.setText("Dolares");
        jChxDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxDolaresActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Monto:");

        jTxtMontoD.setEditable(false);
        jTxtMontoD.setEnabled(false);
        jTxtMontoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMontoDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Pago Cliente:");

        jTxtaPAgoResumen.setColumns(20);
        jTxtaPAgoResumen.setRows(5);
        jScrollPane1.setViewportView(jTxtaPAgoResumen);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTxtPago.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Pago  de cuenta:");

        jBtnGuardarCuenta.setText("GuardarCuenta");
        jBtnGuardarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtPagoC, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtMontoD, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtCodigoT, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jChxDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCbxTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(519, 519, 519)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jBtnValidarT)
                                        .addGap(135, 135, 135)
                                        .addComponent(jBtnGuardarCuenta))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jRdbEfectivo)
                                .addGap(203, 203, 203)
                                .addComponent(jRbdTarjeta)))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdbEfectivo)
                    .addComponent(jRbdTarjeta))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbxTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChxDolares))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTxtNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCodigoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTxtMontoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtPagoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnValidarT)
                    .addComponent(jButton1)
                    .addComponent(jBtnGuardarCuenta))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodigoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoTActionPerformed

    private void jTxtMontoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMontoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMontoDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         jCbxTipoTarjeta.addItem("Visa");
         jCbxTipoTarjeta.addItem("Master Card");
         jCbxTipoTarjeta.setSelectedIndex(-1);
         jChxDolares.setEnabled(false);
         jCbxTipoTarjeta.setEnabled(false);
         jTxtCodigoT.setEnabled(false);
         jTxtNumTarjeta.setEnabled(false);
         jTxtMontoD.setEnabled(false);
         jTxtPagoC.setEnabled(false);
         jTxtPago.setText(String.valueOf(FrmCuenta.cuenta1.Total()));
    }//GEN-LAST:event_formWindowOpened

    private void jBtnValidarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnValidarTActionPerformed
         if(jRdbEfectivo.isSelected()){
             if(!jChxDolares.isSelected()){
              pago1= new Contado(FrmCuenta.cuenta1.Total());
             }
              ((Contado)pago1).setPagoCliente(Integer.parseInt(jTxtPagoC.getText()));  
             JOptionPane.showMessageDialog(null,"El vuelto es: " +(jChxDolares.isSelected()?String.format("%.2f",((Contado)pago1).calculaVueltoDolares()):
            String.format("%.2f",((Contado)pago1).calculaVueltoColones()))
                     + "\nEl pago de la cuenta es:" +pago1.letraMonto()
             ) ;
             if(jChxDolares.isSelected()){
                jTxtaPAgoResumen.setText(((Contado)pago1).display());
             }else{
               jTxtaPAgoResumen.setText(pago1.toString()); 
               }
         }else{
              String tipoTarjeta=(String)jCbxTipoTarjeta.getSelectedItem();
               String numTarjeta=jTxtNumTarjeta.getText();
             if(!validar()&& numTarjeta.length()!=16){
                 JOptionPane.showMessageDialog(null, "El tipo de tarjeta es incorrecta");
                 return;
             }else{
              pago1=new Credito(tipoTarjeta,numTarjeta,FrmCuenta.cuenta1.Total());
            ((Credito)pago1).descuento();
            ((Credito)pago1).montoFinal();
             if(((Credito)pago1).validarTarjeta()){
                JOptionPane.showMessageDialog(null,"Tarjeta Valida"
                        +"\nSu cuenta ha sido cancelada" 
                        + "\nEl pago de la cuenta es:" +pago1.letraMonto()
                ); 
            jTxtaPAgoResumen.setText(pago1.toString());
             }else{
                 JOptionPane.showMessageDialog(null,"Tarjeta Denegada"); 
                 return;
                  }
              }        
         }
            
      
    }//GEN-LAST:event_jBtnValidarTActionPerformed
   public boolean validar(){
        int tipoTarjeta=(int)jCbxTipoTarjeta.getSelectedIndex();
          String numTarjeta=jTxtNumTarjeta.getText();
           switch(tipoTarjeta){
                case 0: 
                   return(numTarjeta.charAt(0)==4)?true:false;
                      
                case 1: 
                   if(numTarjeta.charAt(0)==5 && numTarjeta.charAt(1)>0||numTarjeta.charAt(1)<6){
                       return true;
                   }else{
                       return false;
                   } 
           }  
        return false;
   }
    private void jRdbEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbEfectivoActionPerformed
      jChxDolares.setEnabled(true);
      jCbxTipoTarjeta.setEnabled(false);
      jTxtCodigoT.setEnabled(false);
      jTxtNumTarjeta.setEnabled(false);
      jTxtMontoD.setEnabled(true);
      jTxtPagoC.setEnabled(true);
      jCbxTipoTarjeta.setSelectedIndex(-1);
      jTxtCodigoT.setText("");
      jTxtNumTarjeta.setText("");
    }//GEN-LAST:event_jRdbEfectivoActionPerformed

    private void jRbdTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbdTarjetaActionPerformed
       jChxDolares.setEnabled(false);
      jCbxTipoTarjeta.setEnabled(true);
      jTxtCodigoT.setEnabled(true);
      jTxtNumTarjeta.setEnabled(true);
      jTxtPagoC.setEnabled(false);
      jTxtMontoD.setVisible(false);
      jLabel10.setVisible(false);
      jTxtMontoD.setText("");
      jTxtPagoC.setText("");
    }//GEN-LAST:event_jRbdTarjetaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jChxDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxDolaresActionPerformed
       pago1= new Contado(FrmCuenta.cuenta1.Total());
             if(jChxDolares.isSelected()){
                jTxtMontoD.setText(String.valueOf(((Contado)pago1).convertirDolares()));
             }else{
                 jTxtMontoD.setText("");
             }
    }//GEN-LAST:event_jChxDolaresActionPerformed

    private void jBtnGuardarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarCuentaActionPerformed
       Cuenta guardarCuenta=FrmCuenta.cuenta1;
       guardarCuenta.setPago(pago1);
        try {
                //Agrega el Cuenta al archivo
                Cuenta.agregarCuenta(guardarCuenta);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al grabar el departamento, consulte al administrador\n"+ex.toString());
                System.exit(0);
            }
        
        
        JOptionPane.showMessageDialog(null, "la cuenta se ha guardado");       
    }//GEN-LAST:event_jBtnGuardarCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPagoTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtgTipoPago;
    private javax.swing.JButton jBtnGuardarCuenta;
    private javax.swing.JButton jBtnValidarT;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCbxTipoTarjeta;
    private javax.swing.JCheckBox jChxDolares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRbdTarjeta;
    private javax.swing.JRadioButton jRdbEfectivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCodigoT;
    private javax.swing.JTextField jTxtMontoD;
    private javax.swing.JTextField jTxtNumTarjeta;
    private javax.swing.JTextField jTxtPago;
    private javax.swing.JTextField jTxtPagoC;
    private javax.swing.JTextArea jTxtaPAgoResumen;
    // End of variables declaration//GEN-END:variables
}
