/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVista;

import CapaLogica.TipoUsuario;
import CapaLogica.Usuario;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriela
 */
public class JDlgUsuarios extends javax.swing.JDialog {

    static Usuario adm;
    static Usuario salonero;
    static boolean permiso;
   
    ArrayList<Usuario> arrayUsuarios=new ArrayList();  
    int contA=1;
    int contS=1;
    public JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnAdm = new javax.swing.JButton();
        jBtnSalonero = new javax.swing.JButton();
        jPnlAdm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtAdm = new javax.swing.JTextField();
        jPsdClaveAdm = new javax.swing.JPasswordField();
        jBtnIngreAdm = new javax.swing.JButton();
        jPnlSalonero = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtSalonero = new javax.swing.JTextField();
        jPsdClaveSalo = new javax.swing.JPasswordField();
        jBtnIngreSalinero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jBtnAdm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtnAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        jBtnAdm.setText("Administrador");
        jBtnAdm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAdm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdmActionPerformed(evt);
            }
        });

        jBtnSalonero.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtnSalonero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_Service.png"))); // NOI18N
        jBtnSalonero.setText("Salonero");
        jBtnSalonero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnSalonero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnSalonero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaloneroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Administador ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Clave");

        jBtnIngreAdm.setText("Ingresar");
        jBtnIngreAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngreAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlAdmLayout = new javax.swing.GroupLayout(jPnlAdm);
        jPnlAdm.setLayout(jPnlAdmLayout);
        jPnlAdmLayout.setHorizontalGroup(
            jPnlAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAdmLayout.createSequentialGroup()
                .addGroup(jPnlAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlAdmLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPnlAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPsdClaveAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnlAdmLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jBtnIngreAdm)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPnlAdmLayout.setVerticalGroup(
            jPnlAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAdmLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPnlAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPsdClaveAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jBtnIngreAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Salonero");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Clave");

        jPsdClaveSalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPsdClaveSaloActionPerformed(evt);
            }
        });

        jBtnIngreSalinero.setText("Ingresar");
        jBtnIngreSalinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngreSalineroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlSaloneroLayout = new javax.swing.GroupLayout(jPnlSalonero);
        jPnlSalonero.setLayout(jPnlSaloneroLayout);
        jPnlSaloneroLayout.setHorizontalGroup(
            jPnlSaloneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSaloneroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPnlSaloneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlSaloneroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtSalonero, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlSaloneroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPnlSaloneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIngreSalinero)
                            .addComponent(jPsdClaveSalo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPnlSaloneroLayout.setVerticalGroup(
            jPnlSaloneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSaloneroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPnlSaloneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtSalonero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPnlSaloneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPsdClaveSalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnIngreSalinero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jBtnAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPnlAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnSalonero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnlSalonero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jBtnSalonero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPnlSalonero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdmActionPerformed
        if(jPnlAdm.isVisible()){
            jPnlAdm.setVisible(false);
            jBtnSalonero.setEnabled(true);
        }else{
            jPnlAdm.setVisible(true);
            jBtnSalonero.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnAdmActionPerformed

    private void jBtnSaloneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaloneroActionPerformed
        if(jPnlSalonero.isVisible()){
            jPnlSalonero.setVisible(false);
            jBtnAdm.setEnabled(true);
        }else{
            jPnlSalonero.setVisible(true);
            jBtnAdm.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnSaloneroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         jPnlAdm.setVisible(false);
       jPnlSalonero.setVisible(false);
      arrayUsuarios.add(new Usuario("Jose", "456784567", TipoUsuario.Salonero));
      arrayUsuarios.add(new Usuario("Admin", "123456789", TipoUsuario.Administrador));
      arrayUsuarios.add(new Usuario("David", "23451698", TipoUsuario.Salonero));
      arrayUsuarios.add(new Usuario("Salonero", "987654321", TipoUsuario.Salonero));
      jTxtAdm.requestFocus();
      jTxtSalonero.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void jBtnIngreAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngreAdmActionPerformed
      String pass=jPsdClaveAdm.getSelectedText();
      char[] clave=jPsdClaveAdm.getPassword();
      char[] passNom=jTxtAdm.getText().toCharArray();
        String nom=jTxtAdm.getText();
       adm=new Usuario(nom,pass);
       
        if(contA<3){
            int i ;
        for ( i = 0; i < arrayUsuarios.size(); i++) {
         if(Arrays.equals(clave, arrayUsuarios.get(i).getClave().toCharArray())&&
                    Arrays.equals(passNom, arrayUsuarios.get(i).getNombre().toCharArray())){
                permiso=true;
                this.dispose();
                FrmMenu frmMenu=new FrmMenu();
                frmMenu.setVisible(true);
                frmMenu.setLocationRelativeTo(this);
                
           }
              } 
        if(!permiso){
            JOptionPane.showMessageDialog(null, "Intente de nuevo");
               contA++;
               jTxtAdm.requestFocus();
               jTxtAdm.selectAll();
               return;
       
        }
       
        }else{
         JOptionPane.showMessageDialog(null, "El programa se cerrará");
              this.dispose();      
       }
    }//GEN-LAST:event_jBtnIngreAdmActionPerformed

    private void jBtnIngreSalineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngreSalineroActionPerformed
       
      char[] clave=jPsdClaveSalo.getPassword();
      char[] passNom=jTxtSalonero.getText().toCharArray();
      String nom=jTxtSalonero.getText();
      String pass=jTxtSalonero.getText();
       salonero=new Usuario(nom,pass);
      boolean ingreso=false;
            
      if(contS<3){
        for (int i = 0; i < arrayUsuarios.size(); i++) {
         if(Arrays.equals(clave, arrayUsuarios.get(i).getClave().toCharArray())&&
                    Arrays.equals(passNom, arrayUsuarios.get(i).getNombre().toCharArray())){
               permiso=false;
               ingreso=true;
               this.dispose();
                FrmMenu frmMenu=new FrmMenu();
                frmMenu.setVisible(true);
                frmMenu.setLocationRelativeTo(this);
             
                 }
              } 
        if(!ingreso){
            JOptionPane.showMessageDialog(null, "Intente de nuevo");
               contS++;
               jTxtSalonero.requestFocus();
               jTxtSalonero.selectAll();
               return;
       
           }
        }
      else{
         JOptionPane.showMessageDialog(null, "El programa se cerrará");
              this.dispose();      
       }
    }//GEN-LAST:event_jBtnIngreSalineroActionPerformed

    private void jPsdClaveSaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPsdClaveSaloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPsdClaveSaloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios dialog = new JDlgUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdm;
    private javax.swing.JButton jBtnIngreAdm;
    private javax.swing.JButton jBtnIngreSalinero;
    private javax.swing.JButton jBtnSalonero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPnlAdm;
    private javax.swing.JPanel jPnlSalonero;
    private javax.swing.JPasswordField jPsdClaveAdm;
    private javax.swing.JPasswordField jPsdClaveSalo;
    private javax.swing.JTextField jTxtAdm;
    private javax.swing.JTextField jTxtSalonero;
    // End of variables declaration//GEN-END:variables
}
